version: 2.1

jobs:
  run_tests:
    docker:
      - image: python:3.11.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install poetry
            poetry install --without dev
      - run:
          name: Run tests
          command: |
            pytest --junitxml=test-reports/junit.xml --html=test-reports/pytest_report.html --self-contained-html
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports

workflows:
  build_test:
    jobs:
      - run_tests