version: 2.1

executors:
  python-3-11:
    docker:
      - image: python:3.11

jobs:
  test:
    executor: python-3-11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip
            pip install poetry
            poetry install
      - run:
          name: Run tests
          command: python -m pytest

workflows:
  version: 2
  test:
    jobs:
      - test
