version: 2.1

executors:
  python-3-11:
    docker:
      - image: python:3.11
      - command: 
            apt update
            pip install --upgrade pip
            pip install poetry

jobs:
  test:
    executor: python-3-11
    steps:
      - checkout
      - run:
          name: Run tests
          command: poetry run pytest

workflows:
  version: 2
  test:
    jobs:
      - test
