version: 2.1
orbs:
  python: circleci/python@3.11.4

jobs:
  test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run tests
          command: python -m pytest

workflows:
  version: 2
  test:
    jobs:
      - test
